-- SQL pour créer la table renseignements
-- Exécutez ce code dans le SQL Editor de votre dashboard Supabase

CREATE TABLE IF NOT EXISTS public.renseignements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre TEXT NOT NULL,
    contenu TEXT NOT NULL,
    categorie TEXT DEFAULT 'général',
    status TEXT DEFAULT 'actif',
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ajouter des commentaires pour clarification
COMMENT ON TABLE public.renseignements IS 'Table pour stocker les renseignements du système Gust-IA';
COMMENT ON COLUMN public.renseignements.titre IS 'Titre du renseignement';
COMMENT ON COLUMN public.renseignements.contenu IS 'Contenu du renseignement';
COMMENT ON COLUMN public.renseignements.categorie IS 'Catégorie du renseignement';
COMMENT ON COLUMN public.renseignements.status IS 'Statut (actif, inactif, programmé)';
COMMENT ON COLUMN public.renseignements.start_date IS 'Date de début de validité';
COMMENT ON COLUMN public.renseignements.end_date IS 'Date de fin de validité';

-- Créer des indexes pour améliorer les performances
CREATE INDEX IF NOT EXISTS idx_renseignements_categorie ON public.renseignements(categorie);
CREATE INDEX IF NOT EXISTS idx_renseignements_status ON public.renseignements(status);
CREATE INDEX IF NOT EXISTS idx_renseignements_dates ON public.renseignements(start_date, end_date);

-- Insérer quelques renseignements d'exemple
INSERT INTO public.renseignements (titre, contenu, categorie, status) VALUES
('Bienvenue', 'Bienvenue sur Gust-IA, votre assistant personnel pour la catéchèse!', 'général', 'actif'),
('Horaires', 'Les sessions de catéchèse ont lieu le mercredi de 15h à 17h.', 'horaires', 'actif'),
('Contact', 'Pour contacter un humain, appelez le 221765005555.', 'contact', 'actif'),
('Inscriptions', 'Les inscriptions pour l''année 2024-2025 sont ouvertes jusqu''au 30 septembre.', 'inscriptions', 'actif');