version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - TZ=Africa/Dakar
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    networks:
      - concierge-network

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - concierge-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - concierge-network

volumes:
  redis_data:

networks:
  concierge-network:
    driver: bridge