services:
  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Use default configuration from the image
      AUTHENTICATION_TYPE: jwt
      AUTHENTICATION_JWT_SECRET: evolution_secret_key_change_in_production
      AUTHENTICATION_JWT_EXPIRESIN: 24h

      # Basic configuration
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0

      # Database configuration (this seems to be the missing piece)
      DATABASE_PROVIDER: sqlite

      # Redis disabled for now
      REDIS_ENABLED: false

      # Logging
      LOG_LEVEL: INFO
    networks:
      - ai-concierge_concierge-network
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_qrcodes:/evolution/qrcodes

volumes:
  evolution_instances:
  evolution_qrcodes:

networks:
  ai-concierge_concierge-network:
    external: true